name: Universal DevSecOps Security Pipeline

on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - dev

jobs:

  secret-scan:
    name: Secret Scan - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --report-format=json --report-path=gitleaks-report.json --exit-code 1

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json


  sast:
    name: SAST - CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript   # change if needed

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Analyze
        uses: github/codeql-action/analyze@v4

      - name: Upload SARIF file
        uses: actions/upload-artifact@v4
        with:
          name: codeql-report
          path: "**/*.sarif"


  normalize:
    name: Normalize Reports
    runs-on: ubuntu-latest
    needs: [secret-scan, sast]

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Normalization Script
        run: python scripts/normalize.py

      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: final-security-report
          path: final-security-report.json